name: Node.js CI

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
        
    # instalacao das dependências
    - run: npm install
    
    # execucao dos testes
    - run: npx cypress run
        
    # upload dos vídeos gerados
    - name: Upload videos
      uses: actions/upload-artifact@v2.2.3
      if: always()
      with:
        name: videos
        path: cypress/videos
